image_root: '/home/gs4288/guohao/data/Flickr'
ann_root: '/home/gs4288/guohao/data/Flickr/annotations'
dataset: 'flickr'


# set pretrained as a file path or an url
#output/ELIP-L-noGC/checkpoint_best.pth
pretrained: '/home/gs4288/guohao/ELIP/output/ckpt/model_base_retrieval_flickr.pth'


vit: 'base'
batch_size_train: 50
batch_size_test: 300
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 5e-6
image_size: 384
queue_size: 200
alpha: 0
k_test: 256
negative_all_rank: True
n_gpu: 4

# optimizer
weight_decay: 0.02
min_lr: 0
max_epoch: 20
local_loss: False
gather_with_grad: True
evidential: True
warmup_steps: 1000
grad_clip_norm: 5.0


#adapter
adapter: True

