image_root: '/home/ztao/guohao/data/coco2014/images'
ann_root: '/home/ztao/guohao/data/coco2014/annotations'
dataset: 'coco'

# set pretrained as a file path or an url
pretrained: 'ckpt/model_base_retrieval_coco.pth'
pretrain_clip: 'ViT-L/14'
# size of vit model; base or large

vit: 'base'
batch_size_train: 20
batch_size_test: 36
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

image_size: 224
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

