image_root: '/home/gs4288/guohao/data/coco2014/images'
image_root2017_val: '/home/gs4288/guohao/data/coco/images/val2017'
image_root2017_train: '/home/gs4288/guohao/data/coco/images/train2017'
ann_root2017: '/home/gs4288/guohao/data/coco/annotations'
ann_root: '/home/gs4288/guohao/data/coco2014/annotations'
dataset: 'coco'

# set pretrained as a file path or an url
# /home/gs4288/guohao/ELIP/output/ELIP-5e-5/checkpoint_best.pth
pretrained: '/home/gs4288/guohao/ELIP/output/ELIP-5e-5/checkpoint_best.pth'
pretrain_clip: 'ViT-L/14'
# size of vit model; base or large

batch_size_train: 70
batch_size_test: 140
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 5e-4
image_size: 224
negative_all_rank: True
n_gpu: 4

# optimizer
weight_decay: 0.2
min_lr: 8e-5
max_epoch: 30
local_loss: False
gather_with_grad: True
evidential: True
warmup_steps: 500
grad_clip_norm: 5.0

#adapter
adapter: True
va: True
ta: True
