image_root: '/home/gs4288/guohao/data/coco2014/images'
image_root2017_val: '/home/gs4288/guohao/data/coco/images/val2017'
image_root2017_train: '/home/gs4288/guohao/data/coco/images/train2017'
ann_root2017: '/home/gs4288/guohao/data/coco/annotations'
ann_root: '/home/gs4288/guohao/data/coco2014/annotations'
dataset: 'coco'

# set pretrained as a file path or an url
#output/ELIP-L-noGC/checkpoint_best.pth
pretrained: '/home/gs4288/guohao/ELIP/ckpt/model_base_retrieval_coco.pth'


vit: 'base'
batch_size_train: 50
batch_size_test: 300
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 5e-6
image_size: 384
queue_size: 200
alpha: 0
k_test: 256
negative_all_rank: True
n_gpu: 4

# optimizer
weight_decay: 0.02
min_lr: 0
max_epoch: 15
local_loss: False
gather_with_grad: True
evidential: True
warmup_steps: 1000
grad_clip_norm: 5.0


#adapter
va: True
ta: False

